config/routes.rb
GirlsWhoCode::Application.routes.draw do
  devise_for :users
  get 'dashboard', to: 'pages#dashboard'
  root to: "pages#login", :as => '/'
  get 'resources', to: 'pages#resources'
  get 'about', to: 'pages#about'
  get 'lessons', to: 'lessons#index'
  get "lessons/new" => 'lessons#new', as: 'new_lesson'
  post "lessons/new" => 'lessons#create'
  get "lessons/:id", to: 'lessons#show', as: 'lesson'
  post "lessons/:id" => 'lessons#update'
  get "lessons/:id/edit", to: 'lessons#edit', as: 'edit_lesson'
  delete "lessons/:id" => 'lessons#destroy', as: 'destroy_lesson'


  get 'questions', to: 'questions#index'
  get 'questions/new' => 'questions#new', as: 'new_question'
  post 'questions/new' => 'questions#create'
  get 'questions/:id', to: 'questions#show', as: 'question'
  post 'questions/:id', to: 'questions#update'
  get 'questions/:id/edit', to: 'questions#edit', as: 'edit_question'
  delete 'questions/:id' => 'questions#destroy', as: 'destroy_question'
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  validates :name, :presence => true
  validates :lesson_date, :presence => true
  validates :description, :presence => true
  validates :resources, :presence => true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :questions


  def admin?
    admin
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def check_authorized
    unless current_user.admin?
      redirect_to dashboard_path, :notice => "Not Authorized to View This Page"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!

  def index
  end
end

app/controllers/lessons_controller.rb
require './lib/presenters/lesson_presenter'
class LessonsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_authorized, :only => [:new, :create, :edit, :update, :destroy]
  def index
    @lessons = Lesson.order('lesson_date DESC')
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      redirect_to lesson_path(@lesson), :notice => "Lesson Saved."
    else
      redirect_to new_lesson_path, :notice => "Lesson Not Saved."
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
    @presenter = LessonPresenter.new(@lesson)
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update_attributes(lesson_params)
      redirect_to lesson_path(@lesson), :notice => "Lesson Updated."
    else
      flash[:notice] = @lesson.errors.full_messages
      redirect_to edit_lesson_path(@lesson)
    end
  end

  def destroy
    Lesson.destroy(params[:id])
    redirect_to(lessons_path, notice: "Successfully deleted lesson.")
  end

  protected
  def lesson_params
    params.require(:lesson).permit(:name, :lesson_date, :description, :resources)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
    if !current_user.nil?
      redirect_to '/dashboard'
    else
      render :layout => 'home'
    end
  end

  def dashboard
    @user = current_user
    @current_lesson = Lesson.last
  end

  def resources
  end

  def about
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to question_path(@question), :notice => "Thanks for your question!"
    else
      redirect_to new_question_path, :notice => "Make sure all fields all filled out."
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      direct_to question_path, :notice => "Question Updated."
    else
      flash[:notice] = @question.errors.full_messages
      redirect_to edit_question_path(@question)
    end
  end

  protected
  def question_params
    params.require(:question).permit(:title, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
Home

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Girls Who Code: Chicago Tech Academy</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700|Lobster+Two' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="//use.typekit.net/aqi4cnn.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  </head>
  <body>
    <%= render 'pages/header' %>

    <% if flash[:notice] %>
      <p id="flash_notice"><%= flash[:notice] %></p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html class="intro-cover">
  <head>
    <meta charset="utf-8">
    <title>Girls Who Code - Chicago Tech Academy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700|Lobster+Two' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>    
    <script type="text/javascript" src="//use.typekit.net/aqi4cnn.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  </head>
  <body>
    <%= render 'pages/header' unless params[:action] == 'login' && params[:controller] == 'pages' %>
    <% if flash[:notice] %>
      <p id="flash_notice" class="message_errors"><%= flash[:notice] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/lessons/edit.html.erb
<div class="lessons">
  <h3>Edit Lesson</h3>
  <%= form_tag(lesson_path(@lesson), :method => 'post') do %>
    <div class="row cf">
      <%= label_tag :name %><br />
      <%= text_field(:lesson, :name) %>
      <%= label_tag :lesson_date %><br />
      <%= date_field(:lesson, :lesson_date) %>
      <%= label_tag :description %> (Markdown Support)<br />
      <%= text_area(:lesson, :description) %>
      <%= label_tag :resources %> (Markdown Support)<br />
      <%= text_area(:lesson, :resources) %>
      <%= submit_tag "Edit Lesson" %>
      <%= link_to "All Lessons", lessons_path, :class => "button primary" %>
      <%= link_to "Delete Lesson", destroy_lesson_path(@lesson), :method => 'delete', :class => "button primary", data: {:confirm => "Are you sure you want to delete this lesson?"} %>
      
    </div>
  <% end %>
</div>

app/views/lessons/index.html.erb
<div class="lessons">
  <h2>Lessons</h2>
  <% @lessons.each do |lesson| %>
    <div class="row cf">
      <h3><%= link_to lesson.name, lesson_path(lesson) %></h3>
      <h4><%= lesson.lesson_date.strftime("%b %d, %Y") %></h4>
      <p><%= GitHub::Markdown.render_gfm(lesson.description).html_safe %></p>
    </div>
  <% end %>
  <% if current_user.admin? %>
    <%= link_to "Add Lesson", new_lesson_path, :class => "button primary" %>
  <% end %>
</div>

app/views/lessons/new.html.erb
<div class="lessons">
  <h3>Add Lesson</h3>
  <%= form_tag(new_lesson_path, :method => 'post') do %>
    <div class="row cf">
      <%= label_tag :name %>
      <%= text_field(:lesson, :name) %>
      <%= label_tag :lesson_date %>
      <%= date_field(:lesson, :lesson_date) %><br/>
      <%= label_tag :description %> (Markdown Support)
      <%= text_area(:lesson, :description) %>
      <%= label_tag :resources %> (Markdown Support)
      <%= text_area(:lesson, :resources) %>
      <%= submit_tag "Create Lesson" %>
      <%= link_to "All Lessons", lessons_path, :class => "button primary" %>
    </div>
  <% end %>
</div>

app/views/lessons/show.html.erb
<div class="lessons">
  <h3><%= @lesson.name %></h3>
  <h4><%= @presenter.display_date %></h4>
  <p><%= GitHub::Markdown.render_gfm(@lesson.description).html_safe %></p>
  <p><%= GitHub::Markdown.render_gfm(@lesson.resources).html_safe %></p>

  <%= link_to "Edit Lesson", edit_lesson_path(@lesson), :class => "button primary" %>
</div>

app/views/pages/_header.html.erb
<header>
  <div class="container">
    <a href="/dashboard" class="logo">Girls Who Code</a>
    <div class="session">
      <span class="user-name">
        <% if current_user %>
          Hi, <%= current_user.name %>!
        <% end %>
      </span>
      <%= link_to "Sign Out", destroy_user_session_path, method: "delete", :class => "button sign-out" %>
    </div>
  </div>
  <div class="sub-nav">
      <%= link_to "About", about_path, :class => "button nav" %>
      <%= link_to "Lessons", lessons_path, :class => "button nav" %>
      <%= link_to "Ask a Question", new_question_path, :class => "button nav" %>
      <%= link_to "Resources", resources_path, :class => "button nav" %>
      <%= link_to "Edit Profile", edit_user_registration_path, :class => "button nav" %>
  </div>
</header>

app/views/pages/about.html.erb
<h3>About Girls Who Code</h3>
<section class="cf">
  <p>Girls Who Code is a national nonprofit organization working to close the gender gap in the technology in engineering sections. With support from public and private partners, Girls Who Code works to educate, inspire, and equip high school girls with the skills and resources to pursue opportunities in computing fields.</p>
  <%= link_to "More About Girls Who Code", "http://girlswhocode.com/about-us/", :target => "_blank" %>
</section>

<section class="cf">
<h3>About This Application</h3>
<p>I created this application to help communication with the Chicago Tech Academy Girls Who Code chapter. Users of this application are the girls in the class, and this application will serve as a way to foster communication within our class. Girls will receive an email notification to remind them of our class schedules. Girls can <%= link_to "ask questions", new_question_path %>, can <%= link_to "view resources", resources_path %>, and can <%= link_to "catch up on lessons", lessons_path %>.</p>
</section>

app/views/pages/dashboard.html.erb
<div class="cf row">
  <h3><%= current_user.name %>'s Dashboard</h3>
  <% if @current_lesson %>
    <p>The most recent lesson is <%= link_to @current_lesson.name, lesson_path(@current_lesson) %>
  <% end %>
  <h3>Your Recent Questions</h3>
  <% if current_user.questions %>
    <% current_user.questions.take(5).each do |q| %>
      <%= link_to q.title, question_path(q) %>
    <% end %>
  <% end %>
    <%= link_to "Do you have a question?", new_question_path %>
</div>

app/views/pages/login.html.erb
<header class="intro">
  <div class="container">
    <h1>Girls Who Code</h1>
    <h2>Chicago Tech Academy</h2>
    <%= link_to "Sign In", new_user_session_path, :class => "button sign-in" %> 
    <%= link_to "Sign Up", new_user_registration_path, :class => "button sign-in" %>
  </div>
</header>

app/views/pages/resources.html.erb
<h3>Resources</h3>
<section class="cf">
  <h4>Learn to Code Interactively</h4>
    <%= link_to "Khan Academy", "https://www.khanacademy.org/", :target => "_blank" %></br>
    <p>Khan Academy offers free world-class education for anyone, anywhere. Courses include, science, math, economics and finance, humanities, and computer programming</p>
    <%= link_to "Code Academy", "http://codecademy.com", :target => "_blank" %><br />
    <p>Code Academy is a website where you can learn to code interactively, for free. They offer courses in learning to create interactive websites, games, and killer apps. Languages being taught currently are JavaScript, HTML/CSS, PHP, Python and Ruby.</p>
    <%= link_to "KidsRuby", "http://www.kidsruby.com/", :target => "_blank" %><br />
    <p>KidsRuby makes it fun and easy to learn how to program. You can write code, and run it, and see what it outputs all at the same time. This make it a lot easier to learn.</p>
    <%= link_to "Code.org", "http://code.org/", :target => "_blank" %><br />
    <p>Code.org is where you cna participate in the Hour of Code. After completing the Hour of Code, dive into a 20-hour course that introduces code computer science and programming concepts.</p>
    <%= link_to "Learn Street", "https://www.learnstreet.com/", :target => "_blank" %><br/>
    <p>Learn Street has over 100 interactive exercises in JavaScript, Ruby and Python. It's completely web-based, and allows newbies to quickly start learning the fundamentals of coding. There are also over 100 pratical projects, including how to modify an existing code base to get projects to run, and test your coding skills by leveling up and doing more advanced projects. Projects include games like: Connect Four, Snakes and Ladders, Bubble Sort and more!</p> 
    <%= link_to "Code Avengers", "http://www.codeavengers.com/", :target => "_blank" %><br />
    <p>Code Avengers teaches you how to build games, applications and websites! Learn HTML, CSS and Javascript with gamified code challenges and projects that make learning fun and effective. Includes step-by-step instructions, and features a Free Android application.</p>
    <%= link_to "Scratch", "http://scratch.mit.edu/", :target => "_blank" %><br />
    <p>Scratch is a fun programming language that allows users to create stories, games, and animations and share with others around the world!</p>
    <%= link_to "Mozilla Thimble", "https://thimble.webmaker.org/en-US/", :target => "_blank" %></br>
    <p>Mozilla Thimble lets you view your HTML/CSS automatically in the browser so you can start building websites with automatic feedback</p>
    <h4>Learn to Code with Games</h4>
    <%= link_to "Code Racer", "http://coderace.me/", :target => "_blank" %><br />
    <p>Code Racer is an interactive game to teach coding using your Facebook account to log in. It's a multiplayer live coding game that teaches newbies how to code a basic website using HTML and CSS, and tests intermediate and advanced users on their coding speed and agility. Players race against each other and the clock to complete coding challenges, unlocking weapons and rewards along the way.</p>
    <%= link_to "Code Combat", "http://codecombat.com/", :target => "_blank" %><br />
    <p>Code Combat is a fun way to learn JavaScript, by playing a game! Code Combat is a multiplay game that shows that programming can be a ton of fun.</p> 
    <%= link_to "JS Dares", "http://www.jsdares.com/", :target => "_blank" %><br />
    <p>JS Dares lets you make your own games by learning JavaScript programming. You learn programming by completing dares. Dares are short puzzles in which you have to copy the example, in as few lines as possible. They start simple, and become more difficult as you progress.</p>
    <%= link_to "Turtle Academy", "http://turtleacademy.com/", :target => "_blank" %><br />
    <p>The Turtle Academy makes learning to program easy. You can start creating amazing shapes using the LOGO language.</p>
</section>

app/views/questions/edit.html.erb
<div class="questions">
  <% if current_user.id == @question.user.id %>
    <h3>Edit Question</h3>
    <%= form_tag(question_path(@question), :method => 'post') do %>
      <div class="row cf">
        <%= hidden_field_tag "question[user_id]", current_user.id %>
        <%= label_tag :title %><br />
        <%= text_field(:question, :title) %>
        <%= label_tag :description %><br />
        <%= text_area(:question, :description) %>
        <%= submit_tag "Ask Question" %>
        <%= link_to "All Questions", questions_path, :class => "button primary" %>
      </div>
    <% end %>
  <% else %>
    <h3>You don't have access to this page</h3>
  <% end %>
</div>

app/views/questions/index.html.erb
<div class="questions">
  <% @questions.each do |q| %>
    <div class="row cf">
      <h3><%= link_to q.title, question_path(q) %></h3>
      <h4>Asked by: <%= q.user.name %></h4>
      <p><%= q.description %></p>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="questions">
  <h3>Ask a Question</h3>
  <%= form_tag(new_question_path, :method => 'post') do %>
    <div class="row cf">
      <%= hidden_field_tag "question[user_id]", current_user.id %>
      <%= label_tag :title %><br />
      <%= text_field(:question, :title) %>
      <%= label_tag :description %><br />
      <%= text_area(:question, :description) %>
      <%= submit_tag "Ask Question" %>
      <%= link_to "All Questions", questions_path, :class => "button primary" %>
    </div>
  <% end %>
</div>

app/views/questions/show.html.erb
<div class="questions">
  <h1><%= @question.title %></h1> 
  <h4>Asked by: <%= @question.user.name %></h4>
  <p><%= @question.description %></p>
  <% if current_user.id == @question.user.id %>
    <%= link_to "Edit Question", edit_question_path(@question), :class => "button primary" %>
  <% end %>
</div>